# Generated by Django 6.0 on 2026-01-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('thumbnail', models.URLField()),
                ('url', models.URLField()),
                ('source', models.CharField(default='GameMonetize', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
